### ISSUE TITLE
Consider using Hamster 2 layout

### ISSUE THREAD

**Issue by jtojnar** [projecthamster/hamster-gtk#120]
Hamster 2 uses Overview as the default view:

![hamster-2](https://cloud.githubusercontent.com/assets/705123/19083818/271b1dec-8a64-11e6-93b7-e0e67ee9533a.png)

**Comment by elbenfreund** [comment]
Hamster(2)s original "screen layout" is/was rather strange to begin with. As it was meant to be used with the extension as a launchpad it is more a collection of dialogs that a proper application on its own.
Please provide additional information within the description on what is to be done to close is.

From a stand alone application point of view I do not really see that one usually starts the app to see the overview, but because one wants to track something.

What I want to do at some point however is for the application to accept few CLI options that indicate which screen to open right after startup. That way one could do `hamster-gtk --overview` and start right where you want to be.

**Comment by jtojnar** [comment]
The version I use (from master) feels like application enough. Except for statistics, it offers the full functionality of original hamster (including preferences). It is actually more of a dashboard than overview.

Opening overview in hamster-gtk would not work for me because I use it as a dashboard to access other functionality like adding facts (which overview does not support).

**Comment by elbenfreund** [comment]
Well adding facts etc should ideally live in the main window. From where I stand right now, the overview screen should really be about "displaying" data.

Maybe it would be useful to create a more structure writeup of what screens we want (for version 1.0.0) and what functionality should live in them, what do you think?

**Comment by jtojnar** [comment]
Yes, ideally we should find some UX designer.

**Comment by elbenfreund** [comment]
I did write up my toughts on which screen should deal with what functionality and posted to the dev list.
Comments would be welcome :)
