### ISSUE TITLE
[Feature Request] Calendar WebDAV / CalDAV integration

### ISSUE THREAD

**Issue by ElectricPrism** [projecthamster/hamster-gtk#143]
After starting to use Project Hamster I found myself looking for a save to Calendar extension where I could save my work logs to my local Calendar via Evolution Mail, CalDAV, Google or whatever else.

And then I realized that the feature doesn't exist yet.

I would like to request Saving To and Loading From a calendar as I use Calendars to track my work logs and work history which i can view independent of my workstation on my Phone, etc..

If anyone is willing to foot the work your efforts would be greatly appreciated. :+1:

**Comment by elbenfreund** [comment]
I've split this request into two issues dealing with ical imports / exports independently.
As jan already said, exports are already provided by `hamster-lib` so this is merely a matter of exposing the functionality to the use in the UI.
Imports though will probably not happen for a while (at least 1-2 months) as this is dependend on `hamster-lib` establishing its own general import infrastructure first. Please feel encouraged to watch those two new issues as well in order to stay up to date on any progress.

**Comment by elbenfreund** [comment]
I will close this one in favour or the more specific #144 and #146
