### ISSUE TITLE
Help pls! I can't add new records after 2018-06-19 at 03:56

### ISSUE THREAD

**Issue by perfunke** [projecthamster/hamster-gtk#227]
Hi!  When trying to add a new record now, around wed 2018-06-20 at 03:58  local time (Sweden) they are added to 2018-06-19 (the time is correct) and there is nothing I can do about it.
There are, lately, some instances I noticed that new records were added to the day before. I thought I'd made a mistake and trying again it worked. Now it does not.

Starting Hamster Indicator it shows the records for 2018-06-19 as  "Today". 
In the "Overview", When trying to add new records it automatically fills in 2018-06-20 as the current date but the record ends up in yesterday. 
Like:
"Yesterday, all my troubles seemed so far away..."
https://www.youtube.com/watch?v=jo505ZyaCbA

You can have my db but this message app does not support attaching it's file type.

Hamster version:
 2.91.3. 

OS version:
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

Database rights (I'm user "xhosa")
root@ZBook-15:/home/xhosa/tmp# ls -laR /home/xhosa/.local/share/hamster-applet/
/home/xhosa/.local/share/hamster-applet/:
total 80
drwxr--r--  2 xhosa xhosa  4096 jun 20 04:01 .
drwxr-xr-x 36 xhosa xhosa  4096 jun 19 14:27 ..
-rw-r--r--  1 xhosa xhosa 59392 jun 20 04:01 hamster.db
root@ZBook-15:/home/xhosa/tmp#

**Comment by dmytrokyrychuk** [comment]
I think this issue concerns the old repo: https://github.com/projecthamster/hamster
It is probably caused by the "New day starts at" preference. I think the default value for it is 5:00, the records that began before 5:00 are associated with the previous day. It makes sense to associate activities that happened before you go to sleep with the previous day even though they happen after midnight. You can change the preference to a time before 03:56 if you consider this time to be very early morning rather than very late night :) This will make records after that time to appear in the next day in Overview.

**Comment by elbenfreund** [comment]
Will close as @dmytrokyrychuk is absolutly right this being an issue for ``legacy hamster``.
