### ISSUE TITLE
Installable deb package for Ubuntu 16.04?

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster-gtk#49]
Dear all, 

I would love to provide my feedback on the rebooted Hamster code base. 

However, I am not able to build a deb package for an installation on Ubuntu 16.04 myself. 

Has anyone already built package that he might want to share with me?

Thankfully,

~Robert

**Comment by elbenfreund** [comment]
Hey Robert,

great to hear from you. Whilst dedicated deistribution specific packaging can be addressed later this is not really a pressing matter right now. For actual release within a distribution we will need to reach a much more mature state anyway, so dedicated packaging of development version are not feasable right now. Thats the 'bad news'. Which really it is not. Due to the new code structure and code layout ``hamster-gtk`` can be installed in a fully self contained virtual environment via pip just like any other python package. So far and for now we removed the entire 'buildchain' cruft entirely. You could also use your system wide ``pip`` to install the package, but this is not adviseable.

Right now I am a bit short on time for detailed instructions so here is the gist of it:
* ``apt-get install virtualenvwrapper``
* ``mkvirtualenv hamster-gtk``
* ``workon hamster-gtk``
* Go to you cloned ``hamster-gtk`` repository
* ``git checkout develop``
* ``git pull``
* ``pip install -e .``

Now you can launch the gtk client by invoking ``hamster-gtk``.

Please be advised though:
* There has not been an initial release yet. so things are very unpolished right now.
* There is no way to edit the configuration in the frontend right now. The client uses a mock config provided by ``helpers.get_config``. So if you want to change file locations you would have to edit this by hand.
* Activities may not contain whitespace right now.
* And countless other shortcommings ...

**Comment by orschiro** [comment]
Thank you, Eric!

I managed to get to the point to run `hamster-gtk` but it fails with the following note:

```
(hamster-gtk) orschiro@x230:~/hamster-gtk$ hamster-gtk
Traceback (most recent call last):
  File "/home/orschiro/.virtualenvs/hamster-gtk/bin/hamster-gtk", line 9, in <module>
    load_entry_point('hamster-gtk', 'gui_scripts', 'hamster-gtk')()
  File "/home/orschiro/.virtualenvs/hamster-gtk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/orschiro/.virtualenvs/hamster-gtk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/orschiro/.virtualenvs/hamster-gtk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/orschiro/.virtualenvs/hamster-gtk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/orschiro/hamster-gtk/hamster_gtk/hamster_gtk.py", line 28, in <module>
    import gi
ImportError: No module named gi
```

I might, as you already suggested, better wait for the initial release. 

~Robert

**Comment by elbenfreund** [comment]
well, this one is straight forward I just failed to point this out before :)
hamster-gtk will need access the GTK bindings which are not available via pypi but have to be provided by the system.
on debian like systems something like the following should probably cover this:
``apt-get install python-gi, gir1.2-gtk-3.0, libglib2.0-dev, libgtk-3-dev``
Please note:
* that this is not the actual dependency list (you may need far less, these are just some safe bets)
* if your system runs python3 as default python interpreter you will need ``pythin3-gi`` instead.

After you did install those, you need to make sure that your virtualenv incorporates your system wide ``site-packes`` (other wise it will use *only* those packages installed within the env itself).
If you follow all instructions so far all you need to do is
* activate the environment: ``workon hamster-gtk``
* activate system site dirs: ``toggleglobalsitepackages``

hth, eric.

**Comment by orschiro** [comment]
Alright. I installed all dependencies and enabled the global site packages. 

However, now I am receiving the following error: `ImportError: No module named sceens`.

```
python3-gi is already the newest version (3.20.0-0ubuntu1).
gir1.2-gtk-3.0 is already the newest version (3.18.9-1ubuntu3.1).
libglib2.0-dev is already the newest version (2.48.1-1~ubuntu16.04.1).
libgtk-3-dev is already the newest version (3.18.9-1ubuntu3.1).
python-gi is already the newest version (3.20.0-0ubuntu1).
gir1.2-gtk-3.0 is already the newest version (3.18.9-1ubuntu3.1).
libglib2.0-dev is already the newest version (2.48.1-1~ubuntu16.04.1).
libgtk-3-dev is already the newest version (3.18.9-1ubuntu3.1).
```

**Comment by elbenfreund** [comment]
Yes :) there is a typo in ``develop`` right now. You can
a. wait until later today/tomorrow noon for me to push my current fix to develop
b. look at the trace to see what module features the offending import statement and change it to ``screens``

**Comment by elbenfreund** [comment]
Hamster-GTK 0.10.0 has just been release on pipy.
That mean you should be able to get rid of your old virtualen, create a new pristine one, enable site packages and then just do ``pip install hamster-gtk`` and see where this gets you :)

Have fun, Eric.

**Comment by orschiro** [comment]
It's there. Thank you so much for your work, Eric! :smiley: 

![image](https://cloud.githubusercontent.com/assets/170947/17030640/acee6408-4f70-11e6-9da2-1b609021562f.png)

**Comment by riker09** [comment]
Is it possible to post this information on the homepage?

**Comment by elbenfreund** [comment]
Hey :)
Right now basic "how to install" information is provided in the "first steps" section of the readme.
I agree that having straight forward instructions is crucial, however I think "official" end user related download and install information will only show up on the homepage once we are ready for our first major release. Right now we are still in pre-alpha, so I think the readme is a good enough place to have this information. Please feel free to comment if you feel otherwise.
